[project]
name = "th675-ug-code"
version = "0.1.0"
description = ""
authors = [
    {name = "Thomas Holland",email = "101332229+0thomasholland@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "matplotlib (>=3.10.8,<4.0.0)",
    "numpy (>=2.4.1,<3.0.0)",
    "obspy (>=1.4.2,<2.0.0)",
    "pandas (>=3.0.0,<4.0.0)",
    "pytest (>=9.0.2,<10.0.0)",
    "pyvista (>=0.46.5,<0.47.0)",
    "ipython (>=9.10.0,<10.0.0)",
    "jupyter (>=1.1.1,<2.0.0)",
    "jupytext (>=1.19.1,<2.0.0)"
]

[dependency-groups]
dev = [
    "ruff>=0.13.0,<1.0.0",
    "ty>=0.0.1a19"
]

[tool.ruff]
target-version = "py312"
line-length = 100
extend-exclude = ["*.ipynb"]

[tool.uv]
package = false


[build-system]
requires = ["hatchling>=1.26.3"]
build-backend = "hatchling.build"
